export const units = [
  { number: 1, title: "Expressions" },
  { number: 2, title: "Equations in One Variable" },
  { number: 3, title: "Relations and Functions" },
  { number: 4, title: "Linear and Nonlinear Functions" },
  { number: 5, title: "Creating Linear Equations" },
  { number: 6, title: "Linear Inequalities" },
  { number: 7, title: "Systems of Linear Equations and Inequalities" },
  { number: 8, title: "Exponential Functions" },
  { number: 9, title: "Statistics" },
  { number: 10, title: "Tools of Geometry" },
  { number: 11, title: "Angles and Geometric Figures" },
  { number: 12, title: "Logical Arguments and Line Relationships" },
  { number: 13, title: "Transformations and Symmetry" },
  { number: 14, title: "Triangles and Congruence" },
];

export const lessonSlugs: Record<number, Array<{ slug: string; title: string }>> = {
  1: [
    { slug: "1-1-numerical-expressions", title: "Numerical Expressions" },
    { slug: "1-2-algebraic-expressions", title: "Algebraic Expressions" },
    { slug: "1-3-properties-of-real-numbers", title: "Properties of Real Numbers" },
    { slug: "1-4-distributive-property", title: "Distributive Property" },
    { slug: "1-5-absolute-value-expressions", title: "Expressions Involving Absolute Value" },
    { slug: "1-6-descriptive-modeling-accuracy", title: "Descriptive Modeling and Accuracy" },
  ],
  2: [
    { slug: "2-1-writing-interpreting-equations", title: "Writing and Interpreting Equations" },
    { slug: "2-2-solving-one-step-equations", title: "Solving One-Step Equations" },
    { slug: "2-3-solving-multi-step-equations", title: "Solving Multi-Step Equations" },
    { slug: "2-4-variable-on-each-side", title: "Solving Equations with the Variable on Each Side" },
    { slug: "2-5-absolute-value-equations", title: "Solving Equations Involving Absolute Value" },
    { slug: "2-6-solving-proportions", title: "Solving Proportions" },
    { slug: "2-7-using-formulas", title: "Using Formulas" },
  ],
  3: [
    { slug: "3-1-representing-relations", title: "Representing Relations" },
    { slug: "3-2-functions", title: "Functions" },
    { slug: "3-3-linearity-continuity", title: "Linearity and Continuity of Graphs" },
    { slug: "3-4-intercepts-of-graphs", title: "Intercepts of Graphs" },
    { slug: "3-5-shapes-of-graphs", title: "Shapes of Graphs" },
    { slug: "3-6-sketching-comparing-functions", title: "Sketching Graphs and Comparing Functions" },
  ],
  4: [
    { slug: "4-1-graphing-linear-functions", title: "Graphing Linear Functions" },
    { slug: "4-2-rate-of-change-slope", title: "Rate of Change and Slope" },
    { slug: "4-3-slope-intercept-form", title: "Slope-Intercept Form" },
    { slug: "4-4-transformations-linear-functions", title: "Transformations of Linear Functions" },
    { slug: "4-5-arithmetic-sequences", title: "Arithmetic Sequences" },
    { slug: "4-6-piecewise-step-functions", title: "Piecewise and Step Functions" },
    { slug: "4-7-absolute-value-functions", title: "Absolute Value Functions" },
  ],
  5: [
    { slug: "5-1-writing-slope-intercept", title: "Writing Equations in Slope-Intercept Form" },
    { slug: "5-2-writing-standard-point-slope", title: "Writing Equations in Standard and Point-Slope Forms" },
    { slug: "5-3-scatter-plots-lines-of-fit", title: "Scatter Plots and Lines of Fit" },
    { slug: "5-4-correlation-causation", title: "Correlation and Causation" },
    { slug: "5-5-linear-regression", title: "Linear Regression" },
    { slug: "5-6-inverses-linear-functions", title: "Inverses of Linear Functions" },
  ],
  6: [
    { slug: "6-1-one-step-inequalities", title: "Solving One-Step Inequalities" },
    { slug: "6-2-multi-step-inequalities", title: "Solving Multi-Step Inequalities" },
    { slug: "6-3-compound-inequalities", title: "Solving Compound Inequalities" },
    { slug: "6-4-absolute-value-inequalities", title: "Solving Absolute Value Inequalities" },
    { slug: "6-5-graphing-inequalities-two-variables", title: "Graphing Inequalities in Two Variables" },
  ],
  7: [
    { slug: "7-1-graphing-systems", title: "Graphing Systems of Equations" },
    { slug: "7-2-substitution", title: "Substitution" },
    { slug: "7-3-elimination-addition-subtraction", title: "Elimination Using Addition and Subtraction" },
    { slug: "7-4-elimination-multiplication", title: "Elimination Using Multiplication" },
    { slug: "7-5-systems-of-inequalities", title: "Systems of Inequalities" },
  ],
  8: [
    { slug: "8-1-exponential-functions", title: "Exponential Functions" },
    { slug: "8-2-transformations-exponential", title: "Transformations of Exponential Functions" },
    { slug: "8-3-writing-exponential-functions", title: "Writing Exponential Functions" },
    { slug: "8-4-transforming-exponential-expressions", title: "Transforming Exponential Expressions" },
    { slug: "8-5-geometric-sequences", title: "Geometric Sequences" },
    { slug: "8-6-recursive-formulas", title: "Recursive Formulas" },
  ],
  9: [
    { slug: "9-1-measures-of-center", title: "Measures of Center" },
    { slug: "9-2-representing-data", title: "Representing Data" },
    { slug: "9-3-using-data", title: "Using Data" },
    { slug: "9-4-measures-of-spread", title: "Measures of Spread" },
    { slug: "9-5-distributions-of-data", title: "Distributions of Data" },
    { slug: "9-6-comparing-sets-of-data", title: "Comparing Sets of Data" },
    { slug: "9-7-summarizing-categorical-data", title: "Summarizing Categorical Data" },
    { slug: "9-8-normal-distributions", title: "Normal Distributions" },
  ],
  10: [
    { slug: "10-1-geometric-system", title: "The Geometric System" },
    { slug: "10-2-points-lines-planes", title: "Points, Lines, and Planes" },
    { slug: "10-3-line-segments", title: "Line Segments" },
    { slug: "10-4-distance", title: "Distance" },
    { slug: "10-5-locating-points-number-line", title: "Locating Points on a Number Line" },
    { slug: "10-6-locating-points-coordinate-plane", title: "Locating Points on a Coordinate Plane" },
    { slug: "10-7-midpoints-bisectors", title: "Midpoints and Bisectors" },
  ],
  11: [
    { slug: "11-1-angles-congruence", title: "Angles and Congruence" },
    { slug: "11-2-angle-relationships", title: "Angle Relationships" },
    { slug: "11-3-two-dimensional-figures", title: "Two-Dimensional Figures" },
    { slug: "11-4-transformations-in-plane", title: "Transformations in the Plane" },
    { slug: "11-5-three-dimensional-figures", title: "Three-Dimensional Figures" },
    { slug: "11-6-2d-representations-of-3d", title: "Two-Dimensional Representations of Three-Dimensional Figures" },
    { slug: "11-7-precision-accuracy", title: "Precision and Accuracy" },
    { slug: "11-8-representing-measurements", title: "Representing Measurements" },
  ],
  12: [
    { slug: "12-1-conjectures-counterexamples", title: "Conjectures and Counterexamples" },
    { slug: "12-2-statements-conditionals", title: "Statements, Conditionals, and Biconditionals" },
    { slug: "12-3-deductive-reasoning", title: "Deductive Reasoning" },
    { slug: "12-4-writing-proofs", title: "Writing Proofs" },
    { slug: "12-5-proving-segment-relationships", title: "Proving Segment Relationships" },
    { slug: "12-6-proving-angle-relationships", title: "Proving Angle Relationships" },
    { slug: "12-7-parallel-lines-transversals", title: "Parallel Lines and Transversals" },
    { slug: "12-8-slope-equations-of-lines", title: "Slope and Equations of Lines" },
    { slug: "12-9-proving-lines-parallel", title: "Proving Lines Parallel" },
    { slug: "12-10-perpendiculars-distance", title: "Perpendiculars and Distance" },
  ],
  13: [
    { slug: "13-1-reflections", title: "Reflections" },
    { slug: "13-2-translations", title: "Translations" },
    { slug: "13-3-rotations", title: "Rotations" },
    { slug: "13-4-compositions-of-transformations", title: "Compositions of Transformations" },
    { slug: "13-5-tessellations", title: "Tessellations" },
    { slug: "13-6-symmetry", title: "Symmetry" },
  ],
  14: [
    { slug: "14-1-angles-of-triangles", title: "Angles of Triangles" },
    { slug: "14-2-congruent-triangles", title: "Congruent Triangles" },
    { slug: "14-3-proving-sss-sas", title: "Proving Triangles Congruent: SSS, SAS" },
    { slug: "14-4-proving-asa-aas", title: "Proving Triangles Congruent: ASA, AAS" },
    { slug: "14-5-proving-right-triangles", title: "Proving Right Triangles Congruent" },
    { slug: "14-6-isosceles-equilateral", title: "Isosceles and Equilateral Triangles" },
    { slug: "14-7-triangles-coordinate-proofs", title: "Triangles and Coordinate Proofs" },
  ],
};
